services:
  - type: web
    name: woofdotcom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DBNAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
